Spaceship
Rat49/BootCamp pull request #36
Opened 2018-04-21 00:24 UTC by HeathL

Add interface Drawable and Drawable manager. Spaceship use pool for creating bullets.

2018-04-21 08:46 UTC, HeathL commented
Возникли проблемы с использованием AnimationPlayer для объектов пула. Инициализация пули, взятой из пула, валится с ошибкой. Так как скорее всего анимация для пуль и ракет не пригодится, плееры были заменены на текстуры.

2018-04-22 22:44 UTC, yuyoyuppe requested changes
- каждая последующая пуля вылетает с бОльшей скоростью
- для стрельбы нужен пул спрайтов

2018-04-24 17:26 UTC, BigEch commented on Source/Spaceship/OrdinaryBullet.cpp
> +	float angle = std::atan(bulletDirection.x / -bulletDirection.y) * 180.0f / PI_F;
make functions 'DegreeToRadian and 'RadianToDegree'

2018-04-24 17:26 UTC, BigEch commented on Source/Spaceship/OrdinaryBullet.cpp
> +		angle += 180.0f;
make function 'NormalizeAngle'

2018-04-24 17:26 UTC, BigEch commented on Source/Spaceship/OrdinaryBullet.cpp
> +	SetCoordinates(sf::Vector2f(position.x + bulletDirection.x * _bulletTexture->getSize().y / 2.0f, position.y + bulletDirection.y * _bulletTexture->getSize().y / 2.0f));
You should not depend on 'texture' or some another things to calculate coordinates. what if tomorrow use start to use some another representation of bullet, for example triangle mesh?

2018-04-24 17:26 UTC, BigEch commented on Source/Spaceship/OrdinaryBullet.cpp
> +sf::Sprite* OrdinaryBullet::GetSprite()
const Sprite* ?

2018-04-24 17:26 UTC, BigEch commented on Source/Spaceship/OrdinaryBullet.cpp
> +void OrdinaryBullet::Update(sf::Time& deltaTime)
const sf::Time&

2018-04-24 17:26 UTC, BigEch commented on Source/Spaceship/OrdinaryBullet.h
> +	bool _life;
isAlive?

2018-04-24 17:26 UTC, BigEch commented on Source/Spaceship/Rocket.cpp
> +	: _speedValue(200.0f)
What units do you use to measure speed? meters per second? pixels per second?

2018-04-24 17:26 UTC, BigEch commented on Source/Spaceship/Rocket.cpp
> +void Rocket::Init(sf::Vector2f position, const sf::Vector2f rocketDirection, sf::Texture& rocketTexture)
const sf::Vector2f&

2018-04-24 17:26 UTC, BigEch commented on Source/Spaceship/Rocket.cpp
> +	if (!GetLifeStatus())
GetLifeStatus -> IsAlive()

2018-04-24 17:26 UTC, BigEch commented on Source/SpaceshipTest/SpaceshipTest.cpp
> +	float currentAngle = 0.0f;
Does it used?

2018-04-25 13:04 UTC, Rat49 submitted a review, later dismissed

2018-04-25 13:06 UTC, merged